// ==UserScript==
// @name             Github/Gitlab 导航栏增强
// @description      为 Github/Gitlab 导航栏增加常用链接菜单
// @version          0.1
// @match            *://github.com/*
// @match            *://gitlab.com/*
// @grant            window.onurlchange
// @grant            unsafeWindow
// @namespace        https://github.com/GallenHu/user-scripts
// @homepage         https://github.com/GallenHu
// @author           Gallen
// @icon             data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAACEUExURUxpcRgWFhsYGBgWFhcWFh8WFhoYGBgWFiUlJRcVFRkWFhgVFRgWFhgVFRsWFhgWFigeHhkWFv////////////r6+h4eHv///xcVFfLx8SMhIUNCQpSTk/r6+jY0NCknJ97e3ru7u+fn51BOTsPCwqGgoISDg6empmpoaK2srNDQ0FhXV3eXcCcAAAAXdFJOUwCBIZXMGP70BuRH2Ze/LpIMUunHkpQR34sfygAAAVpJREFUOMt1U+magjAMDAVb5BDU3W25b9T1/d9vaYpQKDs/rF9nSNJkArDA9ezQZ8wPbc8FE6eAiQUsOO1o19JolFibKCdHGHC0IJezOMD5snx/yE+KOYYr42fPSufSZyazqDoseTPw4lGJNOu6LBXVUPBG3lqYAOv/5ZwnNUfUifzBt8gkgfgINmjxOpgqUA147QWNaocLniqq3QsSVbQHNp45N/BAwoYQz9oUJEiE4GMGfoBSMj5gjeWRIMMqleD/CAzUHFqTLyjOA5zjNnwa4UCEZ2YK3khEcBXHjVBtEFeIZ6+NxYbPqWp1DLKV42t6Ujn2ydyiPi9nX0TTNAkVVZ/gozsl6FbrktkwaVvL2TRK0C8Ca7Hck7f5OBT6FFbLATkL2ugV0tm0RLM9fedDvhWstl8Wp9AFDjFX7yOY/lJrv8AkYuz7fuP8dv9izCYH+x3/LBnj9fYPBTpJDNzX+7cAAAAASUVORK5CYII=
// @license          MIT
// @run-at           document-end
// @updateURL        https://fastly.jsdelivr.net/gh/gallenhu/user-scripts@release/github-nav-enhance.user.js
// @downloadURL      https://fastly.jsdelivr.net/gh/gallenhu/user-scripts@release/github-nav-enhance.user.js
// ==/UserScript==
/* eslint-disable */ /* spell-checker: disable */
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports["github-nav-enhance"]=t():e["github-nav-enhance"]=t()}(this,(()=>(()=>{"use strict";var e={};const t=new class{constructor(){this.location={},this.host="",this.origin="",this.location=window.location,this.host=this.location.host,this.origin=this.location.origin}isDomain(e){return this.host.endsWith(e)}};const n=new class{observeDOM(e,t){const n=new(window.MutationObserver||window.WebKitMutationObserver)(t);return n.observe(e,{childList:!0,subtree:!0}),n}};return t.isDomain("github.com")?null===window.onurlchange&&window.addEventListener("urlchange",(function(){const e=document.querySelector('meta[name="user-login"]').getAttribute("content"),t=document.querySelector("nav.d-flex");if(t){const n=`<a class="js-selected-navigation-item Header-link flex-auto mt-md-n3 mb-md-n3 py-2 py-md-3 mr-0 mr-md-3 border-top border-md-top-0 border-white-fade-15" data-ga-click="Header, click, Nav menu - item:marketplace context:user" data-octo-click="marketplace_click" data-octo-dimensions="location:nav_bar" data-selected-links="/${e}?tab=repositories" href="/${e}?tab=repositories">Repositories</a>\n          <a class="js-selected-navigation-item Header-link flex-auto mt-md-n3 mb-md-n3 py-2 py-md-3 mr-0 mr-md-3 border-top border-md-top-0 border-white-fade-15" data-ga-click="Header, click, Nav menu - item:marketplace context:user" data-octo-click="marketplace_click" data-octo-dimensions="location:nav_bar" data-selected-links="/${e}?tab=repositories" href="/${e}?tab=stars">Stars</a>\n         `;-1===t.innerText.toLowerCase().indexOf("repositories")&&t.insertAdjacentHTML("beforeend",n)}})):n.observeDOM(document.querySelector("head"),(function(){const e=unsafeWindow.gon;if(e){const t=e.current_username,n=document.querySelector("ul.navbar-sub-nav"),o=`<ul class="nav navbar-sub-nav">\n        <li class="nav-item">\n            <a href="/dashboard/projects">Repositories</a>\n        </li>\n        <li class="nav-item">\n            <a href="/users/${t}/starred">Stars</a>\n        </li>\n        </ul>\n        `,a=document.querySelector(".title-container");n&&a&&-1===a.innerText.toLowerCase().indexOf("repositories")&&a.insertAdjacentHTML("beforeend",o)}})),e=e.default})()));